language: csharp
sudo: false
solution: ValveResourceFormat.sln
notifications:
  email: false
install:
  - nuget restore ValveResourceFormat.sln
script:
  - xbuild /p:Configuration=Release ValveResourceFormat.sln
  - mono ./packages/NUnit.Console.3.0.1/tools/nunit3-console.exe ./Tests/bin/Release/Tests.dll
