language: csharp
mono: none
dotnet: 2.1.300

notifications:
  email: false

script:
  - dotnet build -c release ./Decompiler/Decompiler.csproj
  - dotnet build -c release ./ValveResourceFormat/ValveResourceFormat.csproj
  - dotnet test ./Tests/Tests.csproj
